fix host app stripping

diff --git a/.github/template/build-host-linux/action.yml b/.github/template/build-host-linux/action.yml
--- a/.github/template/build-host-linux/action.yml
+++ b/.github/template/build-host-linux/action.yml
@@ -76,9 +76,14 @@ runs:
       GOOS: ${{ inputs.goos }}
       GOARCH: ${{ inputs.goarch }}
       CGO_ENABLED: 1
+      CGO_LDFLAGS: "-O2"
       PKG_CONFIG_PATH: "${{ github.workspace }}/libs/.install/lib/pkgconfig"
     run: |
        go build -ldflags='-s -w -extldflags "-I${{ github.workspace }}/libs/.install/include/libusb-1.0 -L${{ github.workspace }}/libs/.install/lib/ -lusb-1.0 -static"' -trimpath -o ./build/tezsign-host-${{ inputs.goos }}-${{ inputs.goarch }} ./app/host
+       if file ./build/tezsign-host-${{ inputs.goos }}-${{ inputs.goarch }} | grep -q "not stripped"; then
+         echo "::error::host binary is not stripped"
+         exit 1
+       fi
 
   - uses: actions/upload-artifact@v7
     with:
